//! Cross-language PG artifact gate: the committed fixture
//! (`fixtures/pg/demo.json`) is generated by the Ruby compiler
//! (`Parsanol::PG`). If Rust can verify its checksum, extract the grammar
//! and parse with it, Ruby and Rust agree on the artifact contract.

use parsanol::pg::{canonical_json, PgError};
use parsanol::portable::{AstArena, PortableParser};
use parsanol::PgArtifact;

const FIXTURE: &str = include_str!("fixtures/pg/demo.json");
const CANONICAL_SAMPLE: &str = include_str!("fixtures/pg/canonical_sample.json");

#[test]
fn loads_and_verifies_the_ruby_compiled_fixture() {
    let artifact = PgArtifact::from_json(FIXTURE).expect("fixture must verify");
    assert_eq!(artifact.version(), Some("1.2.0"));
    assert_eq!(artifact.grammar_name(), Some("Demo"));
    assert_eq!(artifact.shape(), Some("parsanol-tree/v2"));
    assert_eq!(artifact.entry_names(), vec!["identifier"]);
    assert_eq!(artifact.entry_root("identifier").unwrap(), "iso_identifier");
    assert!(artifact
        .source()
        .unwrap()
        .starts_with("grammar Demo version"));
    assert!(artifact.checksum().unwrap().starts_with("sha256:"));
}

#[test]
fn rejects_a_tampered_envelope() {
    let mut value: serde_json::Value = serde_json::from_str(FIXTURE).unwrap();
    value["version"] = serde_json::Value::String("9.9.9".into());
    let text = serde_json::to_string(&value).unwrap();
    match PgArtifact::from_json(&text) {
        Err(PgError::ChecksumMismatch { stored, computed }) => {
            assert!(stored.starts_with("sha256:"));
            assert!(computed.starts_with("sha256:"));
            assert_ne!(stored, computed);
        }
        other => panic!("expected checksum mismatch, got {other:?}"),
    }
}

#[test]
fn extracts_and_parses_the_entry_grammar() {
    let artifact = PgArtifact::from_json(FIXTURE).unwrap();
    let grammar = artifact.grammar("identifier").unwrap();

    let mut arena = AstArena::for_input("ISO CD 12345-89".len());
    let mut parser = PortableParser::new(&grammar, "ISO CD 12345-89", &mut arena);
    parser.parse().expect("the fixture grammar accepts a pubid");

    let mut negative = AstArena::for_input("nonsense".len());
    let mut parser = PortableParser::new(&grammar, "nonsense", &mut negative);
    assert!(
        parser.parse().is_err(),
        "raw input must not parse as a pubid"
    );
}

#[test]
fn rejects_unknown_entries() {
    let artifact = PgArtifact::from_json(FIXTURE).unwrap();
    match artifact.grammar("nope") {
        Err(PgError::UnknownEntry(entry)) => assert_eq!(entry, "nope"),
        other => panic!("expected unknown entry, got {other:?}"),
    }
}

#[test]
fn canonical_json_round_trips_the_ruby_reference_bytes() {
    // The fixture file was generated by Ruby's JSON.generate over a
    // key-sorted payload; canonical_json must reproduce it byte for byte,
    // including lowercase \u00xx control escapes and raw UTF-8.
    let value: serde_json::Value = serde_json::from_str(CANONICAL_SAMPLE).unwrap();
    assert_eq!(canonical_json(&value).unwrap(), CANONICAL_SAMPLE.trim_end());
}

#[test]
fn canonical_json_refuses_floats() {
    let value: serde_json::Value = serde_json::from_str("{\"x\":1.5}").unwrap();
    assert!(matches!(
        canonical_json(&value),
        Err(PgError::FloatInCanonicalJson)
    ));
}
