//! Pattern analysis for bytecode programs
//!
//! This module provides static analysis of pattern properties
//! at compile time. This information can be used to optimize
//! the generated bytecode.
//!
//! # Architecture
//!
//! The pattern analysis follows these principles:
//! - **OOP**: Each struct has a single responsibility
//! - **MECE**: All analysis types are covered distinctly
//! - **Separation of Concerns**: Analysis is separate from compilation
//! - **Open/Closed**: New analysis types can be added without modification
//!
//! # Analysis Types
//!
//! - `FixedLenAnalysis` - patterns with known length
//! - `NullableAnalysis` - patterns that can match empty string
//! - `FirstSetAnalysis` - patterns that predict the first character

use crate::portable::grammar::Atom;

/// Pattern length analysis result
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum PatternLength {
    /// Fixed length pattern (e.g., "a" has length 1)
    Fixed(usize),
    /// Variable length pattern (e.g., "a*" has unknown length)
    #[default]
    Variable,
    /// Pattern cannot match (e.g., lookahead)
    CannotMatch,
}

/// Analyze a pattern to determine its length property
pub struct FixedLenAnalysis;

impl FixedLenAnalysis {
    /// Create a new fixed length analysis
    pub fn new() -> Self {
        Self
    }

    /// Analyze an atom and return its length property
    pub fn analyze(&self, atom: &Atom) -> PatternLength {
        match atom {
            // Fixed length patterns
            Atom::Str { pattern } => PatternLength::Fixed(pattern.len()),
            Atom::Re { pattern } if pattern.len() == 1 => {
                // Single char regex is fixed length
                PatternLength::Fixed(1)
            }

            // Variable length patterns
            Atom::Re { .. } => PatternLength::Variable,
            Atom::Sequence { .. } => PatternLength::Variable,
            Atom::Alternative { .. } => PatternLength::Variable,
            Atom::Repetition { .. } => PatternLength::Variable,

            // Patterns that don't consume input
            Atom::Lookahead { .. } => PatternLength::CannotMatch,
            Atom::Cut => PatternLength::CannotMatch,

            // Named captures preserve the inner pattern's length (need atom index)
            Atom::Named { .. } => PatternLength::Variable,
            Atom::Ignore { .. } => PatternLength::Variable,
            Atom::Entity { .. } => PatternLength::Variable,
            Atom::Custom { .. } => PatternLength::Variable,
        }
    }
}

impl Default for FixedLenAnalysis {
    fn default() -> Self {
        Self::new()
    }
}

/// Pattern nullability analysis result
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum PatternNullability {
    /// Pattern can match empty string
    Nullable,
    /// Pattern cannot match empty string
    #[default]
    NotNullable,
}

/// Analyze whether a pattern can match empty string
pub struct NullableAnalysis;

impl NullableAnalysis {
    /// Create a new nullable analysis
    pub fn new() -> Self {
        Self
    }

    /// Analyze an atom and return whether it can match empty
    pub fn analyze(&self, atom: &Atom) -> PatternNullability {
        match atom {
            // Always nullable (can match empty)
            Atom::Lookahead { .. } => PatternNullability::Nullable,
            Atom::Repetition { min: 0, .. } => PatternNullability::Nullable,
            Atom::Str { pattern } if pattern.is_empty() => PatternNullability::Nullable,

            // Never nullable (cannot match empty)
            Atom::Str { .. } => PatternNullability::NotNullable,
            Atom::Re { .. } => PatternNullability::NotNullable,
            Atom::Sequence { .. } => PatternNullability::NotNullable,
            Atom::Alternative { .. } => PatternNullability::NotNullable,
            Atom::Repetition { .. } => PatternNullability::NotNullable,
            Atom::Named { .. } => PatternNullability::NotNullable,
            Atom::Ignore { .. } => PatternNullability::NotNullable,
            Atom::Entity { .. } => PatternNullability::NotNullable,
            Atom::Cut => PatternNullability::NotNullable,
            Atom::Custom { .. } => PatternNullability::NotNullable,
        }
    }
}

impl Default for NullableAnalysis {
    fn default() -> Self {
        Self::new()
    }
}

/// First character set analysis result
#[derive(Debug, Clone, Default)]
pub struct FirstSetAnalysis {
    /// The character set
    pub charset: Vec<u8>,
    /// Whether the pattern is nullable
    pub nullable: bool,
}

impl FirstSetAnalysis {
    /// Create a new first set analysis
    pub fn new() -> Self {
        Self {
            charset: Vec::new(),
            nullable: false,
        }
    }

    /// Analyze an atom and return the first character set
    pub fn analyze(&self, atom: &Atom) -> FirstSetAnalysis {
        match atom {
            // Single character/string patterns
            Atom::Str { pattern } if pattern.is_empty() => FirstSetAnalysis {
                charset: vec![],
                nullable: true,
            },
            Atom::Str { pattern } => FirstSetAnalysis {
                charset: vec![pattern.as_bytes()[0]],
                nullable: false,
            },

            // Set patterns
            Atom::Re { pattern } => {
                // Parse character class from regex
                let charset = self.parse_charset_from_regex(pattern);
                let nullable = charset.is_empty();
                FirstSetAnalysis { charset, nullable }
            }

            // Combinations (need atom indices)
            Atom::Sequence { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
            Atom::Alternative { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },

            // Repetition: nullable, first set is inner's first set
            Atom::Repetition { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },

            // Patterns with no predictable first set
            Atom::Lookahead { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: true,
            },
            Atom::Cut => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
            Atom::Named { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
            Atom::Ignore { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
            Atom::Entity { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
            Atom::Custom { .. } => FirstSetAnalysis {
                charset: vec![],
                nullable: false,
            },
        }
    }

    fn parse_charset_from_regex(&self, pattern: &str) -> Vec<u8> {
        // Simple implementation: extract first char of pattern
        if let Some(c) = pattern.chars().next() {
            if c == '[' {
                // Character class
                vec![] // Placeholder
            } else {
                vec![c as u8]
            }
        } else {
            vec![]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fixed_len_analysis_str() {
        let analysis = FixedLenAnalysis::new();
        let atom = Atom::Str {
            pattern: "hello".to_string(),
        };
        assert_eq!(analysis.analyze(&atom), PatternLength::Fixed(5));
    }

    #[test]
    fn test_fixed_len_analysis_single_char() {
        let analysis = FixedLenAnalysis::new();
        let atom = Atom::Str {
            pattern: "a".to_string(),
        };
        assert_eq!(analysis.analyze(&atom), PatternLength::Fixed(1));
    }

    #[test]
    fn test_fixed_len_analysis_re() {
        let analysis = FixedLenAnalysis::new();
        let atom = Atom::Re {
            pattern: "[a-z]+".to_string(),
        };
        assert_eq!(analysis.analyze(&atom), PatternLength::Variable);
    }

    #[test]
    fn test_nullable_analysis_empty_str() {
        let analysis = NullableAnalysis::new();
        let atom = Atom::Str {
            pattern: "".to_string(),
        };
        assert_eq!(analysis.analyze(&atom), PatternNullability::Nullable);
    }

    #[test]
    fn test_nullable_analysis_str() {
        let analysis = NullableAnalysis::new();
        let atom = Atom::Str {
            pattern: "a".to_string(),
        };
        assert_eq!(analysis.analyze(&atom), PatternNullability::NotNullable);
    }

    #[test]
    fn test_nullable_analysis_repetition_zero() {
        let analysis = NullableAnalysis::new();
        let atom = Atom::Repetition {
            atom: 0,
            min: 0,
            max: None,
        };
        assert_eq!(analysis.analyze(&atom), PatternNullability::Nullable);
    }

    #[test]
    fn test_first_set_analysis_str() {
        let analysis = FirstSetAnalysis::new();
        let atom = Atom::Str {
            pattern: "hello".to_string(),
        };
        let result = analysis.analyze(&atom);
        assert_eq!(result.charset, vec![b'h']);
        assert!(!result.nullable);
    }

    #[test]
    fn test_first_set_analysis_empty_str() {
        let analysis = FirstSetAnalysis::new();
        let atom = Atom::Str {
            pattern: "".to_string(),
        };
        let result = analysis.analyze(&atom);
        assert!(result.charset.is_empty());
        assert!(result.nullable);
    }

    #[test]
    fn test_fixed_len_analysis_custom() {
        let analysis = FixedLenAnalysis::new();
        let atom = Atom::Custom { id: 1000 };
        assert_eq!(analysis.analyze(&atom), PatternLength::Variable);
    }

    #[test]
    fn test_nullable_analysis_custom() {
        let analysis = NullableAnalysis::new();
        let atom = Atom::Custom { id: 1000 };
        assert_eq!(
            analysis.analyze(&atom),
            PatternNullability::NotNullable
        );
    }

    #[test]
    fn test_first_set_analysis_custom() {
        let analysis = FirstSetAnalysis::new();
        let atom = Atom::Custom { id: 1000 };
        let result = analysis.analyze(&atom);
        assert!(result.charset.is_empty());
        assert!(!result.nullable);
    }
}
