//! The binding-requirements schema: what a language-specific data model
//! must implement for an entry. Derived from the declared bindings plus
//! the artifact's example tests. Port of `Parsanol::PG::Schema` — the
//! TypeScript emission is byte-compatible.

use serde_json::{Map, Value};

use super::{PgArtifact, PgError};

/// The schema document: one record per entry with `root`, `fields`
/// (path -> {type, card[, preprocess]}) and `examples` derived from the
/// artifact's example tests.
pub fn from_artifact(artifact: &PgArtifact) -> Result<Value, PgError> {
    let mut schema = Map::new();
    for entry in artifact.entry_names() {
        let bindings = artifact.bindings(entry);
        let mut fields = Map::new();
        for binding in bindings {
            let Some(object) = binding.as_object() else {
                continue;
            };
            let path = object
                .get("path")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string();
            let mut requirements = Map::new();
            requirements.insert(
                "type".to_string(),
                object
                    .get("type")
                    .and_then(Value::as_str)
                    .unwrap_or("string")
                    .into(),
            );
            requirements.insert(
                "card".to_string(),
                object
                    .get("card")
                    .and_then(Value::as_str)
                    .unwrap_or("1")
                    .into(),
            );
            if let Some(preprocess) = object.get("preprocess").and_then(Value::as_str) {
                requirements.insert("preprocess".to_string(), preprocess.into());
            }
            fields.insert(path, Value::Object(requirements));
        }

        let mut examples: Vec<Value> = Vec::new();
        for test in artifact.tests() {
            let kind = test.get("kind").and_then(Value::as_str);
            let test_entry = test.get("entry").and_then(Value::as_str);
            let relevant =
                (kind == Some("example") && test_entry.is_none()) || test_entry == Some(entry);
            if !relevant {
                continue;
            }
            examples.push(serde_json::json!({
                "input": test.get("input").cloned().unwrap_or(Value::Null),
                "captures": test.get("expect").cloned().unwrap_or(Value::Null),
            }));
        }

        schema.insert(
            entry.to_string(),
            serde_json::json!({
                "root": artifact.entry_root(entry)?,
                "fields": Value::Object(fields),
                "examples": examples,
            }),
        );
    }
    Ok(Value::Object(schema))
}

/// TypeScript materialization types: one interface per entry, one
/// property per bound field. Cards ending in `*` become arrays;
/// `0..1` becomes nullable.
pub fn to_typescript(schema: &Value) -> String {
    let mut lines =
        vec!["// Generated by parsanol pg schema --ts — binding-requirements types.".to_string()];
    if let Some(entries) = schema.as_object() {
        for (entry, data) in entries {
            lines.push(String::new());
            lines.push(format!("export interface {} {{", ts_name(entry)));
            if let Some(fields) = data.get("fields").and_then(Value::as_object) {
                for (path, requirements) in fields {
                    lines.push(format!("  {}: {};", ts_prop(path), ts_type(requirements)));
                }
            }
            lines.push("}".to_string());
        }
    }
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

fn ts_name(entry: &str) -> String {
    entry
        .split(['_', '.'])
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn ts_prop(path: &str) -> String {
    let leaf = if path.contains("[]") {
        path.rsplit("].").next().unwrap_or(path)
    } else {
        path
    };
    // snake_case to camelCase on letter/digit boundaries, as Ruby's gsub:
    // `([A-Za-z0-9])_([a-z])` -> uppercase next char; both the underscore
    // and the next char are consumed by the match.
    let chars: Vec<char> = leaf.chars().collect();
    let mut out = String::with_capacity(leaf.len());
    let mut index = 0;
    while index < chars.len() {
        let ch = chars[index];
        let next = chars.get(index + 1).copied();
        if ch == '_'
            && index > 0
            && next.is_some_and(|n| n.is_ascii_lowercase())
            && chars[index - 1].is_ascii_alphanumeric()
        {
            out.push(next.unwrap().to_ascii_uppercase());
            index += 2;
            continue;
        }
        out.push(ch);
        index += 1;
    }
    out
}

fn ts_type(requirements: &Value) -> String {
    let kind = requirements.get("type").and_then(Value::as_str);
    let card = requirements
        .get("card")
        .and_then(Value::as_str)
        .unwrap_or("1");
    let base = match kind {
        Some("integer") | Some("float") => "number",
        Some("boolean") => "boolean",
        _ => "string",
    };
    if card.ends_with('*') {
        format!("{base}[]")
    } else if card == "0..1" {
        format!("{base} | null")
    } else {
        base.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ts_name_and_prop_follow_ruby() {
        assert_eq!(ts_name("some_entry"), "SomeEntry");
        assert_eq!(ts_name("idf.identifier"), "IdfIdentifier");
        assert_eq!(ts_prop("publisher_name"), "publisherName");
        assert_eq!(ts_prop("a__b"), "a__b");
        assert_eq!(ts_prop("items[].part_number"), "partNumber");
        assert_eq!(ts_prop("year"), "year");
    }

    #[test]
    fn ts_type_cards() {
        assert_eq!(
            ts_type(&serde_json::json!({ "type": "integer", "card": "1" })),
            "number"
        );
        assert_eq!(
            ts_type(&serde_json::json!({ "type": "string", "card": "1*" })),
            "string[]"
        );
        assert_eq!(
            ts_type(&serde_json::json!({ "type": "boolean", "card": "0..1" })),
            "boolean | null"
        );
    }
}
